import { StyleSheet, Platform } from 'react-native';

// --- HR Dashboard: #fece00 (yellow), darker blue, #ffffff (white) ---
const colors = {
  primary: '#011a6b',
  primaryDark: '#010d40',
  sidebar: '#011a6b',
  sidebarHover: 'rgba(255,255,255,0.06)',
  sidebarActive: 'rgba(254,206,0,0.25)',
  accent: '#fece00',
  surface: '#ffffff',
  background: '#ffffff',
  text: '#011a6b',
  textMuted: 'rgba(1,26,107,0.75)',
  border: 'rgba(1,26,107,0.22)',
  success: '#22c55e',
  danger: '#dc3545',
  warning: '#fece00',
};

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      flexDirection: 'row',
      backgroundColor: colors.background,
      position: 'relative' as any,
      ...Platform.select({ web: { height: '100vh' as any, minHeight: '100vh' as any, overflowY: 'auto' as any, overflowX: 'hidden' as any } }),
    },
    /** Narrow: sidebar is off-canvas; see sidebarNarrowDrawer* */
    mobileDrawerBackdrop: {
      position: 'absolute' as any,
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.45)',
      zIndex: 250,
      ...Platform.select({
        web: {
          position: 'fixed' as any,
        },
      }),
    },
    sidebar: {
      width: 240,
      backgroundColor: colors.sidebar,
      borderTopWidth: 4,
      borderTopColor: colors.accent,
      // Sticky sidebar: only the main content scrolls.
      ...Platform.select({
        web: {
          position: 'sticky' as any,
          top: 0,
          height: '100vh' as any,
          maxHeight: '100vh' as any,
          overflow: 'hidden' as any,
          zIndex: 10 as any,
        },
      }),
      ...Platform.select({ web: { boxShadow: '4px 0 24px rgba(0,0,0,0.08)' } }),
    },
    /** Narrow viewport: slide-over drawer (not in document flow). */
    sidebarNarrowDrawer: {
      width: 288,
      maxWidth: '88%' as any,
      borderTopWidth: 4,
      borderTopColor: colors.accent,
      ...Platform.select({
        default: {
          position: 'absolute' as any,
          left: 0,
          top: 0,
          bottom: 0,
          zIndex: 260,
          elevation: 24,
        },
        web: {
          position: 'fixed' as any,
          left: 0,
          top: 0,
          bottom: 0,
          zIndex: 260,
          boxShadow: '8px 0 32px rgba(0,0,0,0.2)',
          transition: 'transform 0.22s ease-out',
        },
      }),
    },
    sidebarNarrowDrawerClosed: {
      transform: [{ translateX: -320 }],
      pointerEvents: 'none' as any,
      ...Platform.select({
        web: {
          visibility: 'hidden' as any,
        },
      }),
    },
    sidebarNarrowDrawerOpen: {
      transform: [{ translateX: 0 }],
      pointerEvents: 'auto' as any,
      ...Platform.select({
        web: {
          visibility: 'visible' as any,
        },
      }),
    },
    sidebarDrawerScroll: {
      flex: 1,
      minHeight: 0,
    },
    sidebarDrawerScrollContent: {
      flexGrow: 1,
      paddingBottom: 28,
    },
    sidebarInner: {
      flex: 1,
      paddingHorizontal: 14,
      // Prevent sidebar from scrolling; main area handles page scroll.
      ...Platform.select({ web: { overflow: 'hidden' as any } }),
    },
    sidebarBrand: {
      alignItems: 'center',
      paddingTop: 24,
      paddingBottom: 24,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255,255,255,0.1)',
    },
    logoImage: {
      width: 52,
      height: 52,
      borderRadius: 12,
      marginBottom: 8,
    },
    logo: {
      fontSize: 15,
      fontWeight: '700',
      color: '#fff',
      textAlign: 'center',
      letterSpacing: 0.2,
    },
    nav: {
      paddingTop: 20,
      paddingBottom: 20,
    },
    navItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 13,
      paddingHorizontal: 14,
      borderRadius: 12,
      marginBottom: 4,
      ...Platform.select({ web: { transition: 'background-color 0.15s ease' } }),
    },
    activeNavItem: {
      backgroundColor: colors.sidebarActive,
    },
    subNav: {
      marginLeft: 36, // aligns under icon+gap
      marginTop: 6,
      marginBottom: 10,
      borderLeftWidth: 1,
      borderLeftColor: 'rgba(255,255,255,0.16)',
      paddingLeft: 12,
    },
    subNavItem: {
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 12,
      marginBottom: 4,
      backgroundColor: 'transparent',
      ...Platform.select({ web: { cursor: 'pointer', transition: 'background-color 0.15s ease' } }),
    },
    subNavItemActive: {
      backgroundColor: 'rgba(255,255,255,0.12)',
    },
    subNavRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    subNavDot: {
      width: 8,
      height: 8,
      borderRadius: 99,
      backgroundColor: 'rgba(255,255,255,0.32)',
      marginRight: 10,
    },
    subNavDotActive: {
      backgroundColor: colors.accent,
    },
    subNavText: {
      fontSize: 14,
      color: 'rgba(255,255,255,0.82)',
      fontWeight: '500',
    },
    subNavTextActive: {
      color: '#fff',
      fontWeight: '700',
    },
    navIcon: {
      width: 24,
      marginRight: 12,
      alignItems: 'center',
    },
    timerText: {
      fontSize: 14,
      fontWeight: 'bold',
      color: '#28a745', // Green for active countdown
    },
    onTimeContainer: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: [{ translateX: -100 }, { translateY: -50 }, { rotate: '-30deg' }],
      zIndex: 1000,
    },
    onTimeText: {
      fontSize: 48,
      fontWeight: 'bold',
      color: 'rgba(40, 167, 69, 0.7)',
      borderWidth: 4,
      borderColor: 'rgba(40, 167, 69, 0.7)',
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
    },
    overdueContainer: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: [{ translateX: -100 }, { translateY: -50 }, { rotate: '-30deg' }],
      zIndex: 1000,
    },
    overdueStampText: {
      fontSize: 48,
      fontWeight: 'bold',
      color: 'rgba(220, 53, 69, 0.7)',
      borderWidth: 4,
      borderColor: 'rgba(220, 53, 69, 0.7)',
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
    },
    navText: {
      fontSize: 16,
      color: 'rgba(255,255,255,0.9)',
      fontWeight: '600',
    },
    activeNavText: {
      fontWeight: '600',
      color: '#fff',
    },
    sidebarBottom: {
      marginTop: 'auto',
      paddingTop: 20,
      borderTopWidth: 1,
      borderTopColor: 'rgba(255,255,255,0.1)',
      paddingBottom: 20,
    },
    mainContent: {
      flex: 1,
      flexDirection: 'column',
      minWidth: 0,
      minHeight: 0,
      ...Platform.select({ web: { overflow: 'visible' } }),
    },
    dashboardContainer: {
      flex: 1,
      flexDirection: 'column',
      minHeight: 0,
    },
    mainDashboardContent: {
      flex: 1,
      padding: 28,
    },
    mainScrollView: {
      flex: 1,
      minWidth: 0,
      minHeight: 0,
      ...Platform.select({
        web: {
          height: '100%' as any,
          maxHeight: '100vh' as any,
          overflowY: 'auto' as any,
          overflowX: 'hidden' as any,
          WebkitOverflowScrolling: 'touch' as any,
        },
      }),
    },
    mainScrollContent: {
      flexGrow: 1,
      padding: 28,
      ...Platform.select({
        web: {
          paddingBottom: 120,
          minHeight: '100%' as any,
        },
      }),
    },
    mainScrollContentNarrow: {
      padding: 16,
      ...Platform.select({
        web: {
          paddingBottom: 96,
          minHeight: '100%' as any,
        },
      }),
    },
    sidePanel: {
      width: 300,
      backgroundColor: colors.background,
      padding: 24,
      borderLeftWidth: 1,
      borderLeftColor: colors.border,
      flexDirection: 'column',
    },
    sidePanelTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 16,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 18,
      paddingHorizontal: 28,
      backgroundColor: colors.surface,
      borderBottomWidth: 3,
      borderBottomColor: colors.accent,
      ...Platform.select({ web: { boxShadow: '0 1px 3px rgba(0,0,0,0.04)' } }),
    },
    headerMobile: {
      paddingVertical: 14,
      paddingHorizontal: 16,
    },
    headerMenuButton: {
      width: 44,
      height: 44,
      marginRight: 8,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(1,26,107,0.06)',
      ...Platform.select({ web: { cursor: 'pointer' as any } }),
    },
    headerMenuButtonPressed: {
      backgroundColor: 'rgba(1,26,107,0.12)',
    },
    headerTitleContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      flex: 1,
      minWidth: 0,
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.text,
      letterSpacing: -0.3,
    },
    headerProfileBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
      ...Platform.select({ web: { cursor: 'pointer' } }),
    },
    contentContainer: {
      padding: 28,
    },
    profileSidebarButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 10,
      borderRadius: 10,
      backgroundColor: 'rgba(255,255,255,0.06)',
      ...Platform.select({ web: { cursor: 'pointer', transition: 'background-color 0.15s ease' } }),
    },
    profileSidebarButtonTextWrap: {
      flex: 1,
      minWidth: 0,
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      paddingHorizontal: 14,
      borderRadius: 10,
      backgroundColor: 'rgba(255,255,255,0.08)',
      ...Platform.select({ web: { cursor: 'pointer' } }),
    },
    profileModalView: {
      width: 440,
      maxWidth: '94%',
      height: 520,
      maxHeight: '88%',
      borderTopWidth: 4,
      borderTopColor: colors.accent,
    },
    profileModalContent: {
      paddingHorizontal: 4,
      paddingBottom: 28,
    },
    profileModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingBottom: 16,
      marginBottom: 8,
      borderBottomWidth: 2,
      borderBottomColor: colors.border,
    },
    profileModalTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.text,
      letterSpacing: -0.3,
    },
    profileSection: {
      backgroundColor: 'rgba(1,26,107,0.04)',
      borderRadius: 14,
      padding: 24,
      marginBottom: 24,
      borderWidth: 1,
      borderColor: colors.border,
    },
    profileSectionLast: {
      marginBottom: 0,
    },
    profileSectionTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 18,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    profileField: {
      marginBottom: 18,
    },
    profileFieldLast: {
      marginBottom: 0,
    },
    profileLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textMuted,
      marginBottom: 8,
    },
    profileInput: {
      borderWidth: 2,
      borderColor: colors.border,
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 16,
      fontSize: 15,
      backgroundColor: colors.surface,
      color: colors.text,
    },
    profileButton: {
      backgroundColor: colors.primary,
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 24,
      alignItems: 'center',
      marginTop: 8,
      ...Platform.select({ web: { cursor: 'pointer' } }),
    },
    profileButtonText: {
      color: '#fff',
      fontSize: 15,
      fontWeight: '700',
    },
    statsRow: {
      flexDirection: 'row',
      marginBottom: 28,
    },
    statsRowCompact: {
      flexDirection: 'column',
    },
    statCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 20,
      marginRight: 16,
      borderWidth: 1,
      borderColor: colors.border,
      ...Platform.select({ web: { boxShadow: '0 1px 3px rgba(0,0,0,0.05)' } }),
    },
    statCardLast: {
      marginRight: 0,
    },
    statCardStacked: {
      marginRight: 0,
      marginBottom: 12,
    },
    statCardLastStacked: {
      marginBottom: 0,
    },
    statValue: {
      fontSize: 28,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.5,
    },
    statLabel: {
      fontSize: 13,
      color: colors.textMuted,
      marginTop: 4,
      fontWeight: '500',
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 18,
      letterSpacing: -0.2,
    },
    itemsGridContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginHorizontal: -8,
    },
    monitoringCard: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 24,
      marginBottom: 24,
      width: '100%',
      borderWidth: 1,
      borderColor: colors.border,
      ...Platform.select({ web: { boxShadow: '0 1px 3px rgba(0,0,0,0.05)' } }),
      elevation: 2,
    },
    itemContainer: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      width: 220,
      margin: 8,
      padding: 22,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      ...Platform.select({ web: { boxShadow: '0 2px 8px rgba(0,0,0,0.06)', transition: 'transform 0.2s ease, box-shadow 0.2s ease, border-color 0.2s ease', cursor: 'pointer' } }),
    },
    itemContainerCompact: {
      width: '100%' as any,
      maxWidth: 440,
      alignSelf: 'center',
    },
    itemContainerHover: {
      borderColor: colors.primary,
      transform: [{ translateY: -3 }],
      ...Platform.select({ web: { boxShadow: '0 12px 28px rgba(14,165,233,0.18)' } }),
    },
    profilePicture: {
      width: 72,
      height: 72,
      borderRadius: 36,
      marginBottom: 14,
      backgroundColor: colors.background,
    },
    itemHeaderText: {
      marginBottom: 6,
      alignItems: 'center',
    },
    itemTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
      textAlign: 'center',
    },
    itemSubtitle: {
      fontSize: 12,
      color: colors.textMuted,
      fontWeight: '500',
    },
    itemDate: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 6,
    },
    itemDetail: {
      fontSize: 14,
      color: '#555',
      lineHeight: 20,
    },
    itemText: {
      fontSize: 14,
      lineHeight: 20,
      color: '#495057',
      marginBottom: 8,
    },
    bold: {
      fontWeight: '600',
      color: colors.text,
    },
    button: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 6,
      marginBottom: 10,
      ...Platform.select({ web: { transition: 'background-color 0.2s ease' } })
    },
    approveButton: {
      backgroundColor: colors.success,
    },
    rejectButton: {
      backgroundColor: colors.danger,
    },
    rejectModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    rejectModalContent: {
      backgroundColor: '#fff',
      borderRadius: 12,
      padding: 20,
      width: '100%',
      maxWidth: 360,
    },
    rejectModalTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 8,
      color: '#333',
    },
    rejectModalSubtitle: {
      fontSize: 14,
      color: '#666',
      marginBottom: 12,
    },
    rejectCommentInput: {
      borderWidth: 1,
      borderColor: '#ccc',
      borderRadius: 8,
      padding: 12,
      fontSize: 14,
      minHeight: 80,
      textAlignVertical: 'top',
      marginBottom: 16,
    },
    rejectModalButtons: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    rejectModalButton: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 8,
      marginLeft: 12,
    },
    rejectModalCancel: {
      backgroundColor: '#e9ecef',
    },
    rejectModalCancelText: {
      color: '#495057',
      fontWeight: '600',
    },
    rejectModalConfirm: {
      backgroundColor: colors.danger,
    },
    rejectModalConfirmText: {
      color: '#fff',
      fontWeight: '600',
    },
    /** Mark-complete / success feedback — not destructive (avoid reuse of rejectModalConfirm red) */
    markCompleteModalPrimaryButton: {
      backgroundColor: colors.primary,
    },
    markCompleteModalPrimaryButtonText: {
      color: '#fff',
      fontWeight: '600',
    },
    reviewButton: {
      backgroundColor: colors.primary,
    },
    reviewButtonHover: {
      backgroundColor: colors.primaryDark,
    },
    submitButton: {
      backgroundColor: colors.warning,
    },
    cancelButton: {
      backgroundColor: colors.textMuted,
    },
    printButton: {
      backgroundColor: colors.primary,
      marginLeft: 8,
    },
    filtersContainer: {
      flexDirection: 'row',
      marginBottom: 20,
    },
    clearFiltersButton: {
      backgroundColor: colors.textMuted,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 5,
    },
    clearFiltersButtonText: {
      color: '#fff',
    },
    // Records tab
    recordsHeader: {
      marginBottom: 20,
    },
    recordsTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.text,
    },
    recordsSubtitle: {
      fontSize: 14,
      color: colors.textMuted,
      marginTop: 4,
    },
    recordsFiltersCard: {
      backgroundColor: '#fff',
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 3,
      elevation: 2,
    },
    recordsFiltersLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 12,
    },
    recordsFiltersRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'flex-end',
    },
    recordsFilterGroup: {
      minWidth: 160,
      marginRight: 12,
      marginBottom: 4,
    },
    recordsFilterLabel: {
      fontSize: 11,
      fontWeight: '500',
      color: '#94a3b8',
      marginBottom: 4,
    },
    recordsClearButton: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 8,
      backgroundColor: colors.background,
      alignSelf: 'flex-end',
    },
    recordsClearButtonText: {
      color: colors.textMuted,
      fontSize: 14,
      fontWeight: '600',
    },
    recordsTableCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      overflow: 'hidden',
      ...Platform.select({
        web: {
          boxShadow: '0 18px 45px rgba(1,26,107,0.10)',
        },
      }),
    },
    recordsTableHorizontalScroll: {
      flexGrow: 0,
    },
    recordsTableInner: {
      minWidth: 1080,
    },
    recordsTableHeader: {
      flexDirection: 'row',
      borderBottomWidth: 3,
      borderBottomColor: colors.accent,
      paddingVertical: 10,
      marginBottom: 4,
      backgroundColor: 'rgba(1,26,107,0.06)',
      paddingHorizontal: 14,
      alignItems: 'center',
    },
    recordsTableHeaderCell: {
      fontWeight: '700',
      fontSize: 13,
      color: colors.primary,
      textAlign: 'left',
    },
    recordsColEmployee: { width: 220, flexGrow: 0, flexShrink: 0, paddingRight: 14 },
    recordsColType: { width: 140, flexGrow: 0, flexShrink: 0, paddingRight: 14 },
    recordsColDate: { width: 150, flexGrow: 0, flexShrink: 0, paddingRight: 14 },
    recordsColStatus: { width: 140, flexGrow: 0, flexShrink: 0, paddingRight: 14 },
    recordsColCampus: { width: 160, flexGrow: 0, flexShrink: 0, paddingRight: 14 },
    recordsColFaculty: { width: 230, flexGrow: 0, flexShrink: 0, paddingRight: 14 },
    recordsColActions: {
      width: 180,
      flexGrow: 0,
      flexShrink: 0,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
    },
    recordsTableRow: {
      flexDirection: 'row',
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(1,26,107,0.14)',
      alignItems: 'center',
    },
    recordsTableRowAlt: {
      backgroundColor: 'rgba(1,26,107,0.03)',
    },
    recordsTableCell: {
      fontSize: 13,
      color: colors.primary,
      fontWeight: '500',
      textAlign: 'left',
    },
    recordsBadgeSlip: {
      alignSelf: 'flex-start',
      paddingVertical: 4,
      paddingHorizontal: 10,
      borderRadius: 20,
      backgroundColor: '#dbeafe',
    },
    recordsBadgeSlipText: {
      fontSize: 12,
      fontWeight: '600',
      color: '#1e40af',
    },
    recordsBadgeOrder: {
      alignSelf: 'flex-start',
      paddingVertical: 4,
      paddingHorizontal: 10,
      borderRadius: 20,
      backgroundColor: '#e0e7ff',
    },
    recordsBadgeOrderText: {
      fontSize: 12,
      fontWeight: '600',
      color: '#3730a3',
    },
    recordsActionsCell: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
    },
    recordsViewBtn: {
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 8,
      backgroundColor: colors.primary,
      ...Platform.select({
        web: {
          cursor: 'pointer',
        },
      }),
    },
    recordsViewBtnText: {
      color: '#fff',
      fontSize: 12,
      fontWeight: '600',
    },
    recordsPrintBtn: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 6,
      backgroundColor: '#fff',
      borderWidth: 1,
      borderColor: colors.border,
      marginLeft: 8,
      ...Platform.select({
        web: {
          cursor: 'pointer',
        },
      }),
    },
    recordsPrintBtnText: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    recordsEmpty: {
      padding: 48,
      alignItems: 'center',
      justifyContent: 'center',
    },
    recordsEmptyTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: colors.text,
      marginTop: 16,
    },
    recordsEmptyText: {
      fontSize: 14,
      color: colors.textMuted,
      marginTop: 8,
    },
    buttonText: {
      color: '#ffffff',
      fontWeight: 'bold',
      fontSize: 14,
    },
    errorText: {
      color: colors.danger,
      textAlign: 'center',
      fontSize: 15,
      marginTop: 24,
      fontWeight: '500',
    },
    emptyText: {
      color: colors.textMuted,
      textAlign: 'center',
      marginTop: 24,
      fontSize: 15,
    },
    tabContainer: {
      flexDirection: 'row',
      marginBottom: 24,
      backgroundColor: colors.background,
      borderRadius: 12,
      padding: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    tab: {
      flex: 1,
      paddingVertical: 12,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 10,
      ...Platform.select({ web: { cursor: 'pointer', transition: 'background-color 0.15s ease' } }),
    },
    activeTab: {
      backgroundColor: colors.accent,
      ...Platform.select({ web: { boxShadow: '0 1px 2px rgba(0,0,0,0.06)' } }),
    },
    tabText: {
      fontSize: 14,
      color: colors.textMuted,
      fontWeight: '600',
    },
    activeTabText: {
      color: colors.primary,
      fontWeight: '700',
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(15, 23, 42, 0.5)',
    },
    modalView: {
      width: 520,
      maxWidth: '95%',
      height: 700,
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 24,
      borderWidth: 1,
      borderColor: colors.border,
      ...Platform.select({ web: { boxShadow: '0 24px 48px rgba(0,0,0,0.12)' } }),
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    closeModalButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: colors.background,
      ...Platform.select({ web: { cursor: 'pointer' } }),
    },
    modalContent: {
      paddingBottom: 20, // Ensure there's space for the buttons
    },
    docValue: {
      fontWeight: 'bold',
      textDecorationLine: 'underline',
    },
    docUniversityName: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#003366',
    },
    docMotto: {
      fontSize: 10,
      fontStyle: 'italic',
    },
    docPassSlipHeader: {
      fontSize: 14,
      fontWeight: 'bold',
      color: '#003366',
      marginTop: 5,
    },
    blueLine: {
      height: 2,
      backgroundColor: '#003366',
      marginTop: 2,
      marginBottom: 5,
      width: '80%',
    },
    mapModalView: {
      height: '80%',
      width: '80%',
    },
    docLogo: {
      width: 60,
      height: 60,
    },
    docTitleContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    trackingNoContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    trackingNoInput: {
      borderBottomWidth: 1,
      borderColor: '#ccc',
      marginLeft: 5,
      padding: 2,
      minWidth: 100,
    },
    docMainTitleContainer: {
      alignItems: 'center',
      marginBottom: 20,
    },
    docMainTitle: {
      fontSize: 20,
      fontWeight: 'bold',
    },
    docSubTitle: {
      fontSize: 14,
      color: '#666',
    },
    signatureTitle: {
      fontSize: 12,
      color: '#666',
      marginTop: 5,
    },
    viewMapButton: {
      marginTop: 10,
      backgroundColor: '#e7f3ff',
      paddingVertical: 8,
      paddingHorizontal: 15,
      borderRadius: 5,
      alignSelf: 'flex-start',
    },
    viewMapButtonText: {
      color: '#003366',
      fontWeight: 'bold',
    },
    docHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 20,
    },
    docRow: {
      marginBottom: 10,
    },
    docSection: {
      marginBottom: 20,
      paddingBottom: 15,
      borderBottomWidth: 1,
      borderBottomColor: '#e0e0e0',
    },
    docInstruction: {
      fontSize: 12,
      color: '#333',
      marginBottom: 6,
      textAlign: 'left',
    },
    docField: {
      fontSize: 16,
    },
    docSignatureRow: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginTop: 30,
    },
    docSignatureContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 40,
      marginBottom: 40,
      paddingTop: 20,
    },
    docSignatureBox: {
      width: '48%',
    },
    docSignatureDisplay: {
      height: 80, 
      justifyContent: 'flex-end',
      marginBottom: 5,
    },
    docSignatureImage: {
      width: 100,
      height: 50,
      alignSelf: 'center',
      marginBottom: -15,
    },
    docSignatureName: {
      fontSize: 16,
      fontWeight: 'bold',
      marginTop: 5,
      textAlign: 'center',
    },
    docSignatureUnderline: {
      borderTopWidth: 1,
      borderColor: '#000',
      textAlign: 'center',
      paddingTop: 2,
      fontSize: 12,
    },
    universityNameContainer: {
      flex: 1,
    },
    headerLine: {
      height: 2,
      backgroundColor: '#3498db',
      marginVertical: 4,
    },
    travelOrderLogo: {
      width: 70,
      height: 70,
      marginHorizontal: 10,
    },
    universityName: {
      fontWeight: 'bold',
      fontSize: 14,
      color: '#2980b9',
    },
    universityMotto: {
      fontSize: 8,
      fontStyle: 'italic',
    },
    docHeaderRight: {
      borderWidth: 1,
      borderColor: '#34495e',
      maxWidth: '45%',
    },
    docInfoBoxHeader: {
      backgroundColor: '#34495e',
      padding: 4,
      alignItems: 'center',
      borderBottomWidth: 1,
      borderColor: '#34495e',
    },
    docInfoBoxContent: {
      backgroundColor: 'white',
      padding: 4,
      alignItems: 'center',
      borderBottomWidth: 1,
      borderColor: '#34495e',
    },
    docInfoTitle: {
      fontSize: 10,
      fontWeight: 'bold',
      color: 'white',
    },
    docInfoContent: {
      fontSize: 12,
      fontWeight: 'bold',
      color: '#000',
    },
    docInfoColumnsContainer: {
      flexDirection: 'row',
      backgroundColor: '#ecf0f1',
    },
    docInfoColumnHeader: {
      flex: 1,
      padding: 4,
      textAlign: 'center',
      borderRightWidth: 1,
      borderColor: '#bdc3c7',
      fontSize: 8,
      color: '#7f8c8d',
      backgroundColor: '#ecf0f1',
    },
    docInfoColumnValue: {
      flex: 1,
      padding: 4,
      textAlign: 'center',
      borderRightWidth: 1,
      borderColor: '#bdc3c7',
      fontSize: 10,
      fontWeight: 'bold',
      backgroundColor: 'white',
    },
    docTitle: {
      textAlign: 'center',
      fontWeight: 'bold',
      fontSize: 16,
      marginVertical: 5,
      textDecorationLine: 'underline',
    },
    revisedText: {
      textAlign: 'left',
      fontSize: 10,
      marginBottom: 10,
    },
    formRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 5,
    },
    formLabel: {
      fontSize: 10,
      marginRight: 5,
    },
    formValue: {
      fontSize: 10,
      fontWeight: 'bold',
      paddingBottom: 2,
      alignSelf: 'flex-start',
    },
    formLabelRight: {
      fontSize: 10,
      marginLeft: 10,
      marginRight: 5,
    },
    directiveText: {
      fontSize: 10,
      marginVertical: 10,
    },
    infoText: {
      fontSize: 10,
      marginBottom: 5,
    },
    signatureSection: {
      marginTop: 20,
    },
    signatureBlock: {
      marginBottom: 20,
    },
    signatureBlockLeft: {
      marginBottom: 20,
      alignItems: 'flex-start',
    },
    recommenderBlock: {
      marginBottom: 16,
    },
    recommenderChiefBlock: {
      marginBottom: 16,
      alignSelf: 'flex-start',
    },
    chiefSignatureDisplay: {
      position: 'relative',
      alignSelf: 'flex-start',
      alignItems: 'center',
      marginBottom: 2,
    },
    chiefSignatureImageContainer: {
      position: 'absolute',
      top: -5,
      left: 0,
      right: 0,
      zIndex: 2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    chiefSignatureNameContainer: {
      alignSelf: 'flex-start',
      borderBottomWidth: 1,
      borderColor: '#000',
      paddingBottom: 2,
      marginTop: 14,
    },
    chiefSignatureLabel: {
      marginTop: 2,
    },
    signatureHeader: {
      fontSize: 10,
      fontWeight: 'bold',
    },
    signatureNameContainer: {
      alignSelf: 'flex-start',
      borderBottomWidth: 1,
      borderColor: '#000',
      paddingBottom: 2,
      marginTop: 15,
    },
    signatureName: {
      fontSize: 12,
      fontWeight: 'bold',
    },
    formInput: {
      fontSize: 10,
      borderBottomWidth: 1,
      borderColor: '#000',
      width: 100,
      padding: 2,
    },
    formDateValue: {
      fontSize: 10,
      fontWeight: 'bold',
      borderBottomWidth: 1,
      borderColor: '#000',
      width: 100,
      padding: 2,
    },
    signaturePadContainer: {
      borderWidth: 1,
      borderColor: '#000',
      marginBottom: 10,
    },
    signatureButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: 200,
    },
    clearButton: {
      backgroundColor: '#6c757d',
      padding: 10,
      borderRadius: 5,
    },
    clearButtonText: {
      color: '#fff',
      fontWeight: 'bold',
    },
    saveButton: {
      backgroundColor: '#007bff',
      padding: 10,
      borderRadius: 5,
    },
    saveButtonText: {
      color: '#fff',
      fontWeight: 'bold',
    },
    signatureModalView: {
      width: 350,
      backgroundColor: 'white',
      borderRadius: 10,
      padding: 20,
      alignItems: 'center',
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 20,
    },
    addSignatureButton: {
      backgroundColor: colors.primary,
      padding: 8,
      borderRadius: 8,
      marginLeft: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    signaturePreview: {
      width: 50,
      height: 25,
      marginLeft: 10,
    },
    signatureModalOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'flex-end',
      backgroundColor: 'rgba(0, 0, 0, 0.2)',
      paddingRight: 50,
      zIndex: 10,
    },
    modalButton: {
      flex: 1,
      marginHorizontal: 5,
      alignItems: 'center',
      marginBottom: 0, // Override default margin
    },
    modalButtonContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingTop: 20,
      borderTopWidth: 1,
      borderTopColor: '#e9ecef',
    },
    formContainer: {
      backgroundColor: colors.surface,
      padding: 28,
      borderRadius: 14,
      marginBottom: 24,
      borderWidth: 1,
      borderColor: colors.border,
      ...Platform.select({ web: { boxShadow: '0 2px 8px rgba(0,0,0,0.04)' } }),
    },
    formTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 20,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      padding: 14,
      marginBottom: 16,
      fontSize: 15,
      backgroundColor: colors.background,
      color: colors.text,
    },
    summaryContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginBottom: 24,
    },
    summaryCard: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 22,
      alignItems: 'center',
      flex: 1,
      marginHorizontal: 8,
      borderWidth: 1,
      borderColor: colors.border,
      ...Platform.select({ web: { boxShadow: '0 2px 8px rgba(0,0,0,0.04)' } }),
    },
    summaryValue: {
      fontSize: 28,
      fontWeight: '800',
      color: colors.primary,
    },
    summaryLabel: {
      fontSize: 13,
      color: colors.textMuted,
      marginTop: 6,
      fontWeight: '500',
    },
    approvedStampContainer: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: [{ translateX: -100 }, { translateY: -50 }, { rotate: '-30deg' }],
      zIndex: 1000,
    },
    approvedStamp: {
      fontSize: 48,
      fontWeight: 'bold',
      color: 'rgba(0, 128, 0, 0.7)', // Green color
      borderWidth: 4,
      borderColor: 'rgba(0, 128, 0, 0.7)', // Green border
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
    },
    rejectedStampContainer: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: [{ translateX: -100 }, { translateY: -50 }, { rotate: '-30deg' }],
      zIndex: 1000,
    },
    rejectedStamp: {
      fontSize: 48,
      fontWeight: 'bold',
      color: 'rgba(255, 0, 0, 0.7)', // Red color
      borderWidth: 4,
      borderColor: 'rgba(255, 0, 0, 0.7)', // Red border
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
    },
    table: {
      width: '100%',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      overflow: 'hidden',
      marginTop: 16,
      backgroundColor: colors.surface,
    },
    tableHeader: {
      flexDirection: 'row',
      backgroundColor: colors.background,
      borderBottomWidth: 1,
      borderColor: colors.border,
    },
    tableHeaderCell: {
      padding: 14,
      fontWeight: '600',
      fontSize: 12,
      color: colors.textMuted,
      textAlign: 'center',
      borderRightWidth: 1,
      borderColor: colors.border,
    },
    tableRow: {
      flexDirection: 'row',
      borderBottomWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
    },
    tableCell: {
      padding: 14,
      textAlign: 'center',
      borderRightWidth: 1,
      borderColor: colors.border,
      color: colors.text,
      fontSize: 14,
    },
    viewButton: {
      backgroundColor: colors.primary,
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 8,
      alignSelf: 'center',
    },
    viewButtonText: {
      color: '#fff',
      fontWeight: '600',
      fontSize: 13,
    },
    issueCtcButton: {
      backgroundColor: '#f4b400',
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 8,
      alignSelf: 'center',
      marginLeft: 8,
    },
    issueCtcButtonText: {
      color: '#011a6b',
      fontWeight: '700',
      fontSize: 13,
    },
    markTravelCompleteButton: {
      backgroundColor: '#16a34a',
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 8,
      alignSelf: 'center',
      marginLeft: 8,
    },
    markTravelCompleteButtonDisabled: {
      opacity: 0.55,
    },
    markTravelCompleteButtonText: {
      color: '#fff',
      fontWeight: '700',
      fontSize: 13,
    },

    // Monitoring table (web-style like UserManagement)
    monitoringTableCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      overflow: 'hidden',
      marginTop: 16,
      ...Platform.select({
        web: {
          boxShadow: '0 18px 45px rgba(1,26,107,0.10)',
        },
      }),
    },
    monitoringTableHorizontalScroll: {
      flexGrow: 0,
    },
    monitoringTableInner: {
      width: '100%',
    },
    monitoringTableHeader: {
      flexDirection: 'row',
      borderBottomWidth: 3,
      borderBottomColor: colors.accent,
      paddingVertical: 10,
      backgroundColor: 'rgba(1,26,107,0.06)',
      paddingHorizontal: 14,
      alignItems: 'center',
    },
    monitoringHeaderText: {
      fontWeight: '700',
      fontSize: 13,
      color: colors.primary,
      textAlign: 'left',
    },
    monitoringTableRow: {
      flexDirection: 'row',
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(1,26,107,0.14)',
      alignItems: 'center',
    },
    monitoringTableRowAlt: {
      backgroundColor: 'rgba(1,26,107,0.03)',
    },
    monitoringRowText: {
      fontSize: 13,
      color: colors.primary,
      fontWeight: '500',
      textAlign: 'left',
    },
    monitoringColEmployee: { flex: 2, minWidth: 180, paddingRight: 14 },
    monitoringColDestination: { flex: 3, minWidth: 220, paddingRight: 14 },
    monitoringColTimeOut: { flex: 1.2, minWidth: 120, paddingRight: 14 },
    monitoringColTimer: { flex: 2, minWidth: 200, paddingRight: 14 },
    monitoringColActions: {
      flex: 1.2,
      minWidth: 140,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
    },
    /** View + Mark complete (and optional CTC); column width from featureFlags / props */
    monitoringColActionsTwoButtons: {
      flex: 0,
      flexGrow: 0,
      flexShrink: 0,
      minWidth: 200,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
    },
    monitoringColActionsThreeButtons: {
      flex: 0,
      flexGrow: 0,
      flexShrink: 0,
      minWidth: 300,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
    },
    monitoringActionsCell: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
    },
    /* CTC certificate modal styles — kept when feature disabled via featureFlags.ts */
    ctcModalView: {
      width: 950,
      maxWidth: '96%',
      height: '88%',
    },
    ctcPaper: {
      borderWidth: 1,
      borderColor: '#111',
      paddingVertical: 16,
      paddingHorizontal: 18,
      backgroundColor: '#fff',
    },
    ctcTopRule: {
      height: 2,
      backgroundColor: '#003366',
      width: '42%',
      marginBottom: 5,
    },
    ctcHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 10,
    },
    ctcUniversityBlock: {
      flex: 1,
      paddingRight: 8,
    },
    ctcUniversityName: {
      fontSize: 26,
      fontWeight: '700',
      color: '#003366',
      lineHeight: 24,
    },
    ctcMotto: {
      fontSize: 10,
      fontStyle: 'italic',
      marginTop: 2,
      marginBottom: 4,
    },
    ctcTitle: {
      fontSize: 22,
      color: '#003366',
      fontWeight: '700',
      marginTop: 6,
    },
    ctcLogo: {
      width: 72,
      height: 72,
      marginLeft: 10,
    },
    ctcDateRow: {
      alignItems: 'flex-end',
      marginBottom: 10,
      alignSelf: 'flex-end',
    },
    ctcDateText: {
      fontSize: 15,
      fontWeight: '600',
      textAlign: 'center',
      borderBottomWidth: 1,
      borderBottomColor: '#222',
      paddingHorizontal: 6,
      paddingBottom: 1,
      alignSelf: 'flex-end',
    },
    ctcDateLabel: {
      fontSize: 12,
      marginTop: 2,
    },
    ctcLineGroup: {
      marginBottom: 8,
      alignItems: 'flex-start',
    },
    ctcLineText: {
      fontSize: 16,
      lineHeight: 20,
      textAlign: 'left',
      fontWeight: '700',
      borderBottomWidth: 1,
      borderBottomColor: '#222',
      paddingHorizontal: 4,
      paddingBottom: 1,
      alignSelf: 'flex-start',
      marginBottom: 1,
    },
    ctcLineLabel: {
      fontSize: 12,
      lineHeight: 16,
      textAlign: 'left',
    },
    ctcBodyText: {
      fontSize: 14,
      lineHeight: 19,
      marginBottom: 6,
    },
    ctcInlineValue: {
      fontWeight: '700',
      textDecorationLine: 'underline',
    },
    ctcChecklistBlock: {
      marginVertical: 8,
      borderTopWidth: 0,
      borderTopColor: '#111',
      paddingTop: 6,
      borderBottomWidth: 0,
      borderBottomColor: '#111',
      paddingBottom: 4,
    },
    ctcChecklistRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      marginBottom: 4,
    },
    ctcChecklistRowIndent: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
      paddingLeft: 22,
    },
    ctcCheckbox: {
      width: 14,
      height: 14,
      borderWidth: 1,
      borderColor: '#222',
      marginRight: 8,
      marginTop: 1,
    },
    ctcInlineBlank: {
      borderBottomWidth: 1,
      borderBottomColor: '#222',
      minWidth: 110,
      height: 14,
      marginHorizontal: 4,
    },
    ctcInlineBlankShort: {
      borderBottomWidth: 1,
      borderBottomColor: '#222',
      minWidth: 180,
      height: 14,
      marginHorizontal: 4,
    },
    ctcChecklistItem: {
      fontSize: 13,
      lineHeight: 18,
    },
    ctcSignatureBlockTop: {
      marginTop: 12,
      alignItems: 'flex-end',
    },
    /** Right-aligned on page; inner content centers sig on name */
    ctcSignatureNameCluster: {
      alignItems: 'center',
      alignSelf: 'flex-end',
      marginTop: 4,
    },
    ctcSignatureNameWithSig: {
      alignItems: 'center',
      alignSelf: 'center',
    },
    ctcSignatureImage: {
      height: 80,
      width: 120,
      resizeMode: 'contain' as const,
      alignSelf: 'center',
      /** Pulls signature down so its visual center sits over the name line */
      marginBottom: -40,
      zIndex: 1,
    },
    ctcSignatureBlockBottom: {
      marginTop: 10,
      alignItems: 'flex-end',
    },
    ctcUnderlineFieldMedium: {
      minWidth: 300,
      borderBottomWidth: 1,
      borderBottomColor: '#222',
      alignItems: 'center',
    },
    ctcSignatureName: {
      fontSize: 15,
      fontWeight: '700',
      textAlign: 'center',
      marginTop: 2,
    },
    ctcSignatureNameDynamic: {
      fontSize: 15,
      fontWeight: '700',
      textAlign: 'center',
      marginTop: 0,
      borderBottomWidth: 1,
      borderBottomColor: '#222',
      paddingHorizontal: 6,
      paddingBottom: 1,
      alignSelf: 'center',
      zIndex: 0,
    },
    ctcSignatureRole: {
      fontSize: 12,
      marginTop: 4,
      textAlign: 'center',
      alignSelf: 'center',
    },
    salaryContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderColor: '#000',
      paddingBottom: 2,
      alignSelf: 'flex-start',
    },
    pesoSign: {
      fontSize: 10,
      marginRight: 2,
    },
  });